# Generated by Django 4.2.13 on 2024-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('year_founded', models.CharField(max_length=255, null=True)),
                ('size_range', models.CharField(max_length=255, null=True)),
                ('locality', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('linked_url', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('current_emplyee_estimate', models.IntegerField(null=True)),
                ('total_emplyee_estimate', models.IntegerField(null=True)),
                ('emplyee_from', models.DateTimeField(auto_now_add=True)),
                ('emplyee_to', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_companies',
            },
        ),
    ]
